### ISSUE TITLE
http://sinatra-book.gittr.com link broken

### ISSUE THREAD

**Issue by rberger** [sinatra/sinatra-book#71]
The link to the rendered book doesn't have a DNS entry. I get:

```
The server at sinatra-book.gittr.com can't be found, because the DNS lookup failed. DNS is 
the network service that translates a website's name to its Internet address. This error is 
most often caused by having no connection to the Internet or a misconfigured network. It can
 also be caused by an unresponsive DNS server or a firewall preventing Google Chrome
from accessing the network.

Error code: ERR_NAME_NOT_RESOLVED
```

**Comment by jeremyricketts** [comment]
The link on http://www.sinatrarb.com/faq.html#deploy still points to http://sinatra-book.gittr.com

**Comment by cschneid** [comment]
Thank you for fixing the link - much appreciated. My personal server situation is all screwed up.

**Comment by StevenNunez** [comment]
I bought http://www.sinatra-book.com/ and am pointing it to http://sinatra-org-book.herokuapp.com/ to make updating the books and docs easier. @zzak If you want to add that as a domain on heroku, go ahead.

**Comment by fwolfst** [comment]
The issue(s) still persist. @StevenNunez: also sinatra-book.com is not pointing in the right direction anymore. I'd favour not to link to a build in either sinatra FAQ nor in this projects description than having a broken link.

**Comment by zzak** [comment]
It's been a while since I've looked into this project, but I think it'd be nice if we could generate a static version of the book, we should be able to host it at http://sinatrarb.com/sinatra-book/ as per github pages static page hosting.

/cc @kgrz @stjhimy

**Comment by sixtyfive** [comment]
I just bought sinatra-books.com again (as it was up for grabs and curiously not taken by a domain troll) and pointed it at the herokuapp site as Steven had already done. Unfortunately there are still a number of links to broken sites and some of Google's hits don't help, either. Perhaps at least the link at https://github.com/sinatra/sinatra-book could be corrected to something that works?

**Comment by sixtyfive** [comment]
And the one at http://recipes.sinatrarb.com/p/testing ("… along with the *book* and readme.") It links to the old, broken URL, too.

**Comment by kgrz** [comment]
@sixtyfive Updated the link in the github repo homepage to point to the heroku app page

**Comment by sixtyfive** [comment]
Looked around for a bit and couldn't find anymore broken links. Can be closed now?

**Comment by zzak** [comment]
Yeah, let's close this for now. I'd be happy if someone wanted to hook up static generation somewhere and point a sub-domain there (e.g. book.sinatrarb.com) as I _think_ I still have access to that
