### ISSUE TITLE
invalid byte sequence in US-ASCII

### ISSUE THREAD

**Issue by enliven-** [sinatra/sinatra-book#72]
I am getting

`invalid byte sequence in US-ASCII`

when I run 

`bundle exec rake book:build`

I'm using Ruby 2.1.2

**Comment by dayvough** [comment]
Getting the same error.

**Comment by kgrz** [comment]
Hmm, I'm not seeing this error with ruby 2.1.2p95. What's the patch level on Ruby 2.1.2 where you faced this issue @enliven-?
